### ISSUE TITLE
CUDA error 400 when convert onnx to tensorrt model

### ISSUE THREAD

**Issue by KDD2018** [mohamedsamirx/YOLOv12-TensorRT-CPP#4]
CUDA error 400 at /home/ai-admin/ai-proj/YOLOv12-TensorRT-CPP/src/YOLOv12.cpp:103yolov12-tensorrt: /home/ai-admin/ai-proj/YOLOv12-TensorRT-CPP/src/YOLOv12.cpp:103: YOLOv12::~YOLOv12(): Assertion `0' failed.

![Image](https://github.com/user-attachments/assets/fc9b20d9-db4f-4838-9013-7ce484316c7a)

**Comment by mohamedsamirx** [comment]
Hello,  

Thank you for your comments and information. I’ll double-check everything. Just a quick note: the repo was fully developed using Google Colab, and you can find the link in the repo. There might be some typos, so please refer to the notebook link for accuracy.

**Comment by KDD2018** [comment]
Oh, I'm sorry that I 'm not familiar with CPP. Could you help me to solve the problem above?

**Comment by mohamedsamirx** [comment]
Yes sure i will take a look on it today

**Comment by mohamedsamirx** [comment]
The issue has been resolved now. Please feel free to open a new issue if any problems arise again.
